export const ADD_PRODUCTS ='ADD_PRODUCTS';
export const PRODUCTS_LOADING ='PRODUCTS_LOADING';
export const PRODUCTS_FAILED ='PRODUCTS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOGIN_SUCCESS_CHECK= 'LOGIN_SUCCESS_CHECK'

export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED= 'SIGNUP_FAILED'
export const REQUEST_SIGNUP_CREDENTIALS= 'REQUEST_SIGNUP_CREDENTIALS'
